import { getDefaultContext } from "@/lib/api/helper";
import * as reportService from "@/lib/domain/report.service";
import { FileText, Sparkles, Clock, CheckCircle2, AlertTriangle } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function ReportsPage() {
  const ctx = await getDefaultContext();
  const [dailyRes, portfolioRes] = await Promise.all([
    reportService.generateDailyReport(ctx),
    reportService.generatePortfolioReport(ctx),
  ]);

  const daily = dailyRes.ok ? dailyRes.data.content : {};
  const portfolio = portfolioRes.ok ? portfolioRes.data.content : {};

  return (
    <div className="max-w-6xl mx-auto space-y-8 pb-16">
      <div>
        <h1 className="text-2xl font-black text-white flex items-center gap-2.5">
          <FileText className="w-6 h-6 text-purple-400" />
          Autonomous Executive Reports
        </h1>
        <p className="text-xs text-slate-400 mt-1">
          Auto-generated daily standups and portfolio health diagnostics generated by Operion.
        </p>
      </div>

      {/* 1. DAILY REPORT */}
      <div className="glass-panel p-4 sm:p-6 rounded-2xl border border-slate-800 space-y-4 sm:space-y-5">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2 text-indigo-400 font-bold text-sm">
            <Sparkles className="w-4 h-4" />
            <span>{daily.title || "Daily Operational Brief"}</span>
          </div>
          <span className="text-[11px] font-mono text-slate-500">
            Generated: {new Date(daily.generatedAt || Date.now()).toLocaleTimeString()}
          </span>
        </div>

        <p className="text-xs sm:text-sm text-slate-300 leading-relaxed bg-slate-900/60 p-3.5 sm:p-4 rounded-xl border border-slate-800/80">
          {daily.summary}
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 sm:gap-3 text-xs">
          <div className="p-3 rounded-xl bg-slate-900 border border-slate-800">
            <p className="text-slate-400">Blocked Items</p>
            <p className="text-lg font-bold text-rose-400 mt-0.5">{daily.blockedTasks?.length || 0}</p>
          </div>
          <div className="p-3 rounded-xl bg-slate-900 border border-slate-800">
            <p className="text-slate-400">Due Today</p>
            <p className="text-lg font-bold text-cyan-400 mt-0.5">{daily.dueTodayTasks?.length || 0}</p>
          </div>
          <div className="p-3 rounded-xl bg-slate-900 border border-slate-800">
            <p className="text-slate-400">Overdue Tasks</p>
            <p className="text-lg font-bold text-amber-400 mt-0.5">{daily.overdueTasks?.length || 0}</p>
          </div>
        </div>
      </div>

      {/* 2. PORTFOLIO REPORT */}
      <div className="glass-panel p-4 sm:p-6 rounded-2xl border border-slate-800 space-y-4 sm:space-y-5">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2 text-cyan-400 font-bold text-sm">
            <CheckCircle2 className="w-4 h-4" />
            <span>{portfolio.title || "Cross-Project Portfolio Review"}</span>
          </div>
          <span className="text-[11px] font-mono text-slate-500">
            Total Projects: {portfolio.totalProjects || 0}
          </span>
        </div>

        <div className="grid grid-cols-3 gap-3 text-center text-xs">
          <div className="p-3 rounded-xl bg-slate-900 border border-slate-800">
            <p className="text-emerald-400 font-semibold">On Track</p>
            <p className="text-xl font-bold text-white mt-0.5">{portfolio.onTrackCount || 0}</p>
          </div>
          <div className="p-3 rounded-xl bg-slate-900 border border-slate-800">
            <p className="text-amber-400 font-semibold">At Risk</p>
            <p className="text-xl font-bold text-white mt-0.5">{portfolio.atRiskCount || 0}</p>
          </div>
          <div className="p-3 rounded-xl bg-slate-900 border border-slate-800">
            <p className="text-rose-400 font-semibold">Blocked</p>
            <p className="text-xl font-bold text-white mt-0.5">{portfolio.blockedCount || 0}</p>
          </div>
        </div>
      </div>
    </div>
  );
}
